import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/hook/provider";

export const metadata: Metadata = {
  title: "ACT TABLE",
  description: "Generated by create next app",
  icons: {
    icon: "/a3.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
        style={{
          overscrollBehaviorX: "none", //  ป้องกันการเลื่อนในแนวนอน (ปัดซ้าย/ขวา)
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
