import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/hook/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ACT TABLE",
  description: "Generated by create next app",
  icons: {
    icon: "/a3.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          overscrollBehaviorX: "none", //  ป้องกันการเลื่อนในแนวนอน (ปัดซ้าย/ขวา)
        }}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
